### ISSUE TITLE
style our page

### ISSUE THREAD

**Issue by jjocelynn** [jjocelynn/WikiGo#8]
As an User I want a landding page with a minimalism style 
Also  a landding page that be attractive to me
Also that be intuitive and simple to use

Acceptance criteria
It is complete
When I use bootstrap to bring style to the page
When I use other thirdparty styling library to style my page
when I get  an intuitive page
When I get a simple use page

**Comment by Ishaval** [comment]
Complete the task


![Image](https://user-images.githubusercontent.com/117535044/216204731-d408e7d0-fc3f-4060-8e1f-a9dab885fb8f.png)
